### ISSUE TITLE
Migrate Device Agent to FlowFuse branding

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/device-agent#194]
### Description

Whilst we've been working through this under the banner of https://github.com/FlowFuse/admin/issues/211, I wanted to dedicated issue for the Device Agent as there are a few pieces to get right in one go and wanted to make sure we tracked them properly.

The plan is to rename the Device Agent's npm module to `@flowfuse/device-agent`. However we will cross-publish to both the old and new module name for a period of time to ease the migration.

```[tasklist]
### Tasks
- [x] Update package.json to `@flowfuse/device-agent`
- [x] Update repo secrets - see below
- [x] Update publish workflow to both flowforge and flowfuse modules
- [x] Update workflow to cross publish to both flowforge and flowfuse containers
- [x] Update README to reflect renaming
- [x] Update to use `/opt/flowfuse-device` as the default config dir - with fallback support for old name
- [x] Add startup log message if found to be installed as `@flowforge..` pointing to the new module name
- [x] Update docs on migration
```

We need to update some repo-level secrets:

 - `NPM_PUBLISH_TOKEN_FLOWFORGE` - the token for publishing to old npm org
 - `NPM_PUBLISH_TOKEN` - the token for publishing to the new org
 - `DOCKER_HUB_PASSWORD_FLOWFORGE` - the password for the old dockerhub account
 - `DOCKER_HUB_PASSWORD` - the password for the new dockerhub account

**Comment by knolleary** [comment]
All tasks complete pending a review and merge of the main doc updates
